### ISSUE TITLE
Missing dependancy specific; xcb, install failing, and a dependency update.

### ISSUE THREAD

**Issue by nan0s7** [arcnmx/screenstub#18]
For some reason on *buntu the package `libxcb-xtest0-dev` was not installed and was needed for the cargo install method.

`libddcutil` is up to version 0.9.1 as of writing this issue, don't know if this matters or not.

Using `cargo install --force --git https://github.com/arcnmx/screenstub` results in a build error, something to do with `libddcutil`. 

**Non-verbose output:**
``  = note: /tmp/cargo-installiZkuWj/release/deps/libddcutil-7964ee5212c8d6a0.rlib(ddcutil-7964ee5212c8d6a0.ddcutil3-2e623f04ad1649742f657a0c095dafb7.rs.rcgu.o): In function `ddcutil::display::Display::vcp_get_value':
          ddcutil3-2e623f04ad1649742f657a0c095dafb7.rs:(.text._ZN7ddcutil7display7Display13vcp_get_value17hc1127e6bc7a2b451E+0x1c): undefined reference to `ddca_get_any_vcp_value'``

**Verbose output:**
``Caused` by:
  process didn't exit successfully: `rustc --crate-name screenstub src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg feature="default" --cfg feature="screenstub-config" --cfg feature="screenstub-ddc" --cfg feature="with-ddcutil" -C metadata=c9ea77663d3cf9cf -C extra-filename=-c9ea77663d3cf9cf --out-dir /tmp/cargo-installiZkuWj/release/deps -L dependency=/tmp/cargo-installiZkuWj/release/deps --extern env_logger=/tmp/cargo-installiZkuWj/release/deps/libenv_logger-65e517b706b2370f.rlib --extern futures_cpupool=/tmp/cargo-installiZkuWj/release/deps/libfutures_cpupool-edf73c135176b190.rlib --extern tokio_fuse=/tmp/cargo-installiZkuWj/release/deps/libtokio_fuse-3172fa2b0c9902f1.rlib --extern tokio_core=/tmp/cargo-installiZkuWj/release/deps/libtokio_core-d9c16dd40a3ebb06.rlib --extern input_linux=/tmp/cargo-installiZkuWj/release/deps/libinput_linux-7961404e568e24ae.rlib --extern screenstub_ddc=/tmp/cargo-installiZkuWj/release/deps/libscreenstub_ddc-084e4b07fe2ba6f3.rlib --extern tokio_process=/tmp/cargo-installiZkuWj/release/deps/libtokio_process-e57f1dbfa30157d3.rlib --extern tokio_unzip=/tmp/cargo-installiZkuWj/release/deps/libtokio_unzip-e7cfa083daad4933.rlib --extern screenstub_x=/tmp/cargo-installiZkuWj/release/deps/libscreenstub_x-a12415a505fe442a.rlib --extern screenstub_event=/tmp/cargo-installiZkuWj/release/deps/libscreenstub_event-575c6bbc9bebc47b.rlib --extern screenstub_config=/tmp/cargo-installiZkuWj/release/deps/libscreenstub_config-7c5ef5636709cb1c.rlib --extern clap=/tmp/cargo-installiZkuWj/release/deps/libclap-51720dc86236b065.rlib --extern futures=/tmp/cargo-installiZkuWj/release/deps/libfutures-348e6343c6b0c45c.rlib --extern screenstub_uinput=/tmp/cargo-installiZkuWj/release/deps/libscreenstub_uinput-3b2e93e118cf50c1.rlib --extern screenstub_qmp=/tmp/cargo-installiZkuWj/release/deps/libscreenstub_qmp-8eba3a58c660da81.rlib --extern failure=/tmp/cargo-installiZkuWj/release/deps/libfailure-295ba8a17e69c4ff.rlib --extern log=/tmp/cargo-installiZkuWj/release/deps/liblog-008287a8b2b7e5f3.rlib --extern result=/tmp/cargo-installiZkuWj/release/deps/libresult-f2a70c18493fd52f.rlib --extern serde_yaml=/tmp/cargo-installiZkuWj/release/deps/libserde_yaml-68b40ddf89fd63f1.rlib --extern tokio_fd=/tmp/cargo-installiZkuWj/release/deps/libtokio_fd-72ab858071be0832.rlib --extern tokio_timer=/tmp/cargo-installiZkuWj/release/deps/libtokio_timer-112046626e474c93.rlib --cap-lints allow -L native=/tmp/cargo-installiZkuWj/release/build/backtrace-sys-adc91b712a83ef0a/out/.libs` (exit code: 101)``

**Comment by arcnmx** [comment]
1. Yeah, readme doesn't include the specific xcb extensions required. Full list is in the [CI yaml](https://github.com/arcnmx/screenstub/blob/master/.travis.yml#L12), would probably be a good idea to link to that from readme or otherwise include the full list for debian/ubuntu.

2. [ddcutil-rs](https://github.com/arcnmx/ddcutil-rs) has not been updated for libddcutil 0.9, and still requires 0.8.6. You'll need to downgrade in order for install/compile to work, as that is the cause of the error.

Work on moving away from ddcutil as a dependency is currently ongoing, the intention is to switch over to [a pure rust DDC implementation that can also be used on the Windows side as well](https://github.com/arcnmx/ddcset-rs). Not sure if/when I'll get a chance to look at the ddcutil 0.9 changes to fix that in the interim...

**Comment by nan0s7** [comment]
Awesome, thanks for the quick reply! The less dependencies needed is obviously way better, but your software is, what, version 0.0.1? According to the Rust installer thingo. So take your time! I appreciate the work you've put into it already! :)

I'll let you know how it goes with the downgrade.

**Comment by arcnmx** [comment]
Dependency issues should be mostly resolved now - they've been reduced to just xcb and udev, and are listed in the README.
